version: '3.8'

services:
  backend:
    build:
      context: . # Dockerfile이 프로젝트 루트에 있음
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis # Redis 서비스에 의존
    environment:
      # Spring Boot가 Redis를 찾을 수 있도록 호스트명 설정
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # EKS 배포를 위한 외부 DB 설정 (로컬에서는 H2 기본값 사용)
      # SPRING_DATASOURCE_URL: jdbc:postgresql://your-rds-endpoint:5432/your_db
      # SPRING_DATASOURCE_USERNAME: your_db_user
      # SPRING_DATASOURCE_PASSWORD: your_db_password
      # SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    # networks 항목 제거

  frontend:
    build:
      context: ./frontend # Dockerfile이 frontend 디렉토리에 있음
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 호스트 3000번 포트를 컨테이너 80번 포트에 연결 (Nginx)
    depends_on:
      - backend # 백엔드 서비스에 의존
    # networks 항목 제거

  redis:
    image: redis:6-alpine # 경량 Redis 이미지 사용
    ports:
      - "6379:6379"
    # networks 항목 제거

# networks 섹션 제거
