# Spring Boot Application Properties

# Server configuration
server:
  port: 8080

# Database configuration (H2 for development, replace with your actual DB)
spring:
  datasource:
    url: jdbc:h2:mem:baseball_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Other configurations can be added here
